---
# tasks file for install_jenkins
#

- name: Add jenkins repository
  ansible.builtin.yum_repository:
    name: jenkins-repo
    description: EPEL YUM repo
    baseurl: https://pkg.jenkins.io/redhat-stable
    enabled: yes
    gpgcheck: yes
    gpgkey: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
  notify: 
    - clean dnf cache
    - update dnf cache
    - update yum cache

- name: install jenkins
  package:
    name: jenkins
    state: present


- name: start jenkins
  service: 
     name: jenkins
     state: started 
     enabled: yes
